all:
	cd hs_case_study_additional_details_f1/ && make
	cd additional_case_studies_f2/ && make
	cd additional_simulation_studies_f3/ && make

clean:
	cd hs_case_study_additional_details_f1/ && make clean
	cd additional_case_studies_f2/ && make clean
	cd additional_simulation_studies_f3/ && make clean

